-- =====================================================
-- 更新查询配置表中的SQL，排除空字符串返回值
-- 2026-04-30 修改：添加 AND xxx != '' 条件排除空字符串
-- =====================================================

UPDATE tjfx_QUERY_CONFIG
SET QUERY_SQL = 'SELECT DISTINCT SYSTEM_SOURCE_NO as code, SYSTEM_SOURCE_NO as name FROM EXAM_TASK WHERE SYSTEM_SOURCE_NO IS NOT NULL AND SYSTEM_SOURCE_NO != '''' ORDER BY SYSTEM_SOURCE_NO'
WHERE FIELD_NAME = 'system';

UPDATE tjfx_QUERY_CONFIG
SET QUERY_SQL = 'SELECT DISTINCT r.REPORTER_NAME as code, r.REPORTER_NAME as name FROM EXAM_REPORT r INNER JOIN EXAM_TASK t ON r.EXAM_TASK_ID = t.EXAM_TASK_ID WHERE r.REPORTER_NAME IS NOT NULL AND r.REPORTER_NAME != '''' AND (@PARENT_VALUE = '''' OR t.SYSTEM_SOURCE_NO = @PARENT_VALUE) ORDER BY r.REPORTER_NAME'
WHERE FIELD_NAME = 'reporter';

UPDATE tjfx_QUERY_CONFIG
SET QUERY_SQL = 'SELECT DISTINCT r.REVIEWER_NAME as code, r.REVIEWER_NAME as name FROM EXAM_REPORT r INNER JOIN EXAM_TASK t ON r.EXAM_TASK_ID = t.EXAM_TASK_ID WHERE r.REVIEWER_NAME IS NOT NULL AND r.REVIEWER_NAME != '''' AND (@PARENT_VALUE = '''' OR t.SYSTEM_SOURCE_NO = @PARENT_VALUE) ORDER BY r.REVIEWER_NAME'
WHERE FIELD_NAME = 'reviewer';

UPDATE tjfx_QUERY_CONFIG
SET QUERY_SQL = 'SELECT DISTINCT t.TECHNICIAN_NAME as code, t.TECHNICIAN_NAME as name FROM EXAM_TASK t WHERE t.TECHNICIAN_NAME IS NOT NULL AND t.TECHNICIAN_NAME != '''' AND (@PARENT_VALUE = '''' OR t.SYSTEM_SOURCE_NO = @PARENT_VALUE) ORDER BY t.TECHNICIAN_NAME'
WHERE FIELD_NAME = 'technician';

UPDATE tjfx_QUERY_CONFIG
SET QUERY_SQL = 'SELECT DISTINCT t.EXEC_DEPT_NAME as code, t.EXEC_DEPT_NAME as name FROM EXAM_TASK t WHERE t.EXEC_DEPT_NAME IS NOT NULL AND t.EXEC_DEPT_NAME != '''' AND (@PARENT_VALUE = '''' OR t.SYSTEM_SOURCE_NO = @PARENT_VALUE) ORDER BY t.EXEC_DEPT_NAME'
WHERE FIELD_NAME = 'department';

UPDATE tjfx_QUERY_CONFIG
SET QUERY_SQL = 'SELECT DISTINCT t.EXAM_CATEGORY_NAME as code, t.EXAM_CATEGORY_NAME as name FROM EXAM_TASK t WHERE t.EXAM_CATEGORY_NAME IS NOT NULL AND t.EXAM_CATEGORY_NAME != '''' AND (@PARENT_VALUE = '''' OR t.SYSTEM_SOURCE_NO = @PARENT_VALUE) ORDER BY t.EXAM_CATEGORY_NAME'
WHERE FIELD_NAME = 'category';

UPDATE tjfx_QUERY_CONFIG
SET QUERY_SQL = 'SELECT DISTINCT t.ENCOUNTER_TYPE_NAME as code, t.ENCOUNTER_TYPE_NAME as name FROM EXAM_TASK t WHERE t.ENCOUNTER_TYPE_NAME IS NOT NULL AND t.ENCOUNTER_TYPE_NAME != '''' AND (@PARENT_VALUE = '''' OR t.SYSTEM_SOURCE_NO = @PARENT_VALUE) ORDER BY t.ENCOUNTER_TYPE_NAME'
WHERE FIELD_NAME = 'patientType';

UPDATE tjfx_QUERY_CONFIG
SET QUERY_SQL = 'SELECT DISTINCT REPORT_RESULT_STATUS as code, REPORT_RESULT_STATUS as name FROM EXAM_REPORT WHERE REPORT_RESULT_STATUS IS NOT NULL AND REPORT_RESULT_STATUS != '''' ORDER BY REPORT_RESULT_STATUS'
WHERE FIELD_NAME = 'resultStatus';

GO

-- 更新白名单表中的SQL
UPDATE tjfx_QUERY_WHITELIST
SET ALLOWED_SQL = 'SELECT DISTINCT SYSTEM_SOURCE_NO as code, SYSTEM_SOURCE_NO as name FROM EXAM_TASK WHERE SYSTEM_SOURCE_NO IS NOT NULL AND SYSTEM_SOURCE_NO != '''' ORDER BY SYSTEM_SOURCE_NO'
WHERE FIELD_NAME = 'system';

UPDATE tjfx_QUERY_WHITELIST
SET ALLOWED_SQL = 'SELECT DISTINCT r.REPORTER_NAME as code, r.REPORTER_NAME as name FROM EXAM_REPORT r INNER JOIN EXAM_TASK t ON r.EXAM_TASK_ID = t.EXAM_TASK_ID WHERE r.REPORTER_NAME IS NOT NULL AND r.REPORTER_NAME != '''' AND (@PARENT_VALUE = '''' OR t.SYSTEM_SOURCE_NO = @PARENT_VALUE) ORDER BY r.REPORTER_NAME'
WHERE FIELD_NAME = 'reporter';

UPDATE tjfx_QUERY_WHITELIST
SET ALLOWED_SQL = 'SELECT DISTINCT r.REVIEWER_NAME as code, r.REVIEWER_NAME as name FROM EXAM_REPORT r INNER JOIN EXAM_TASK t ON r.EXAM_TASK_ID = t.EXAM_TASK_ID WHERE r.REVIEWER_NAME IS NOT NULL AND r.REVIEWER_NAME != '''' AND (@PARENT_VALUE = '''' OR t.SYSTEM_SOURCE_NO = @PARENT_VALUE) ORDER BY r.REVIEWER_NAME'
WHERE FIELD_NAME = 'reviewer';

UPDATE tjfx_QUERY_WHITELIST
SET ALLOWED_SQL = 'SELECT DISTINCT t.TECHNICIAN_NAME as code, t.TECHNICIAN_NAME as name FROM EXAM_TASK t WHERE t.TECHNICIAN_NAME IS NOT NULL AND t.TECHNICIAN_NAME != '''' AND (@PARENT_VALUE = '''' OR t.SYSTEM_SOURCE_NO = @PARENT_VALUE) ORDER BY t.TECHNICIAN_NAME'
WHERE FIELD_NAME = 'technician';

UPDATE tjfx_QUERY_WHITELIST
SET ALLOWED_SQL = 'SELECT DISTINCT t.EXEC_DEPT_NAME as code, t.EXEC_DEPT_NAME as name FROM EXAM_TASK t WHERE t.EXEC_DEPT_NAME IS NOT NULL AND t.EXEC_DEPT_NAME != '''' AND (@PARENT_VALUE = '''' OR t.SYSTEM_SOURCE_NO = @PARENT_VALUE) ORDER BY t.EXEC_DEPT_NAME'
WHERE FIELD_NAME = 'department';

UPDATE tjfx_QUERY_WHITELIST
SET ALLOWED_SQL = 'SELECT DISTINCT t.EXAM_CATEGORY_NAME as code, t.EXAM_CATEGORY_NAME as name FROM EXAM_TASK t WHERE t.EXAM_CATEGORY_NAME IS NOT NULL AND t.EXAM_CATEGORY_NAME != '''' AND (@PARENT_VALUE = '''' OR t.SYSTEM_SOURCE_NO = @PARENT_VALUE) ORDER BY t.EXAM_CATEGORY_NAME'
WHERE FIELD_NAME = 'category';

UPDATE tjfx_QUERY_WHITELIST
SET ALLOWED_SQL = 'SELECT DISTINCT t.ENCOUNTER_TYPE_NAME as code, t.ENCOUNTER_TYPE_NAME as name FROM EXAM_TASK t WHERE t.ENCOUNTER_TYPE_NAME IS NOT NULL AND t.ENCOUNTER_TYPE_NAME != '''' AND (@PARENT_VALUE = '''' OR t.SYSTEM_SOURCE_NO = @PARENT_VALUE) ORDER BY t.ENCOUNTER_TYPE_NAME'
WHERE FIELD_NAME = 'patientType';

UPDATE tjfx_QUERY_WHITELIST
SET ALLOWED_SQL = 'SELECT DISTINCT REPORT_RESULT_STATUS as code, REPORT_RESULT_STATUS as name FROM EXAM_REPORT WHERE REPORT_RESULT_STATUS IS NOT NULL AND REPORT_RESULT_STATUS != '''' ORDER BY REPORT_RESULT_STATUS'
WHERE FIELD_NAME = 'resultStatus';

GO

PRINT '查询配置表SQL已更新完成，已添加空字符串排除条件';
