-- 内镜系统医生工作量统计（仅审核和发布状态，统计本月数据）
-- 连接本地WiNEX_PACS数据库
USE WiNEX_PACS;

-- 定义日期变量（4月1日到4月16日）
DECLARE @StartDate DATETIME = '2026-04-01 00:00:00';  -- 4月1日
DECLARE @EndDate   DATETIME = '2026-04-16 23:59:59';  -- 4月16日 23:59:59

-- 使用CTE获取去重后的任务数据
WITH TaskData AS (
    SELECT DISTINCT
        r.REPORTER_NAME,
        t.EXAM_TASK_ID,
        t.CREATED_AT,
        r.EXAM_CONCLUSION_PLAIN_TEXT,
        MAX(ri.EXAM_ITEM_NAME) AS EXAM_ITEM_NAME
    FROM EXAM_REPORT r
    INNER JOIN EXAM_TASK t ON r.EXAM_TASK_ID = t.EXAM_TASK_ID AND t.IS_DEL = 0
    LEFT JOIN EXAM_CHARGE_ITEM ri ON t.EXAM_TASK_ID = ri.EXAM_TASK_ID AND ri.IS_DEL = 0
    WHERE r.IS_DEL = 0
      AND t.SYSTEM_SOURCE_NO = 'EIS'
      AND t.EXAM_TASK_STATUS >= 50
      AND t.CREATED_AT >= @StartDate
      AND t.CREATED_AT <= @EndDate
      AND r.REPORTER_NAME IS NOT NULL
    GROUP BY r.REPORTER_NAME, t.EXAM_TASK_ID, t.CREATED_AT, r.EXAM_CONCLUSION_PLAIN_TEXT
)
SELECT 
    REPORTER_NAME AS 医生姓名, 
    -- 胃镜统计（按照检查项目）
    COUNT(CASE WHEN (EXAM_ITEM_NAME LIKE N'%胃镜%' OR EXAM_ITEM_NAME LIKE N'%胃+肠%' OR EXAM_ITEM_NAME LIKE N'%胃肠镜%') AND NOT (EXAM_ITEM_NAME LIKE N'%14碳%') THEN EXAM_TASK_ID END) AS 胃镜, 
    -- 无痛胃镜（检查项目）
    COUNT(CASE WHEN (EXAM_ITEM_NAME LIKE N'%无%痛%胃镜%' OR EXAM_ITEM_NAME LIKE N'%无%痛%胃+肠%' OR EXAM_ITEM_NAME LIKE N'%无%痛%胃肠镜%' OR EXAM_ITEM_NAME LIKE N'%无%痛%超声胃镜%') AND NOT (EXAM_ITEM_NAME LIKE N'%14碳%') THEN EXAM_TASK_ID END) AS 无痛胃镜, 
    -- 普通胃镜（检查项目）
    COUNT(CASE WHEN ((EXAM_ITEM_NAME LIKE N'%胃镜%' OR EXAM_ITEM_NAME LIKE N'%胃+肠%' OR EXAM_ITEM_NAME LIKE N'%胃肠镜%') AND EXAM_ITEM_NAME NOT LIKE N'%无%痛%') AND NOT (EXAM_ITEM_NAME LIKE N'%14碳%') THEN EXAM_TASK_ID END) AS 普通胃镜, 
    -- 胃电切（诊断描述）
    COUNT(CASE WHEN (EXAM_ITEM_NAME LIKE N'%胃镜%' OR EXAM_ITEM_NAME LIKE N'%胃+肠%') AND EXAM_CONCLUSION_PLAIN_TEXT LIKE N'%电切%' THEN EXAM_TASK_ID END) AS 胃电切, 
    -- 胃ESD（诊断描述）
    COUNT(CASE WHEN (EXAM_ITEM_NAME LIKE N'%胃镜%' OR EXAM_ITEM_NAME LIKE N'%胃+肠%') AND EXAM_CONCLUSION_PLAIN_TEXT LIKE N'%ESD%' THEN EXAM_TASK_ID END) AS 胃ESD, 
    -- 胃EMR（诊断描述）
    COUNT(CASE WHEN (EXAM_ITEM_NAME LIKE N'%胃镜%' OR EXAM_ITEM_NAME LIKE N'%胃+肠%') AND EXAM_CONCLUSION_PLAIN_TEXT LIKE N'%EMR%' THEN EXAM_TASK_ID END) AS 胃EMR, 
    -- 套扎（诊断描述）
    COUNT(CASE WHEN EXAM_CONCLUSION_PLAIN_TEXT LIKE N'%套扎%' THEN EXAM_TASK_ID END) AS 套扎, 
    -- 硬化（诊断描述）
    COUNT(CASE WHEN EXAM_CONCLUSION_PLAIN_TEXT LIKE N'%硬化%' THEN EXAM_TASK_ID END) AS 硬化, 
    -- 支架（诊断描述）
    COUNT(CASE WHEN EXAM_CONCLUSION_PLAIN_TEXT LIKE N'%支架%' THEN EXAM_TASK_ID END) AS 支架, 
    -- 异物（诊断描述）
    COUNT(CASE WHEN EXAM_CONCLUSION_PLAIN_TEXT LIKE N'%异物%' THEN EXAM_TASK_ID END) AS 异物, 
    -- 超声胃镜
    COUNT(CASE WHEN (EXAM_ITEM_NAME LIKE N'%超声%' OR EXAM_ITEM_NAME LIKE N'%CN%') AND (EXAM_ITEM_NAME LIKE N'%胃%' OR EXAM_CONCLUSION_PLAIN_TEXT LIKE N'%胃%') THEN EXAM_TASK_ID END) AS 超声胃镜, 
    -- 胃内置管
    COUNT(CASE WHEN (EXAM_ITEM_NAME LIKE N'%超声%' OR EXAM_ITEM_NAME LIKE N'%CN%') AND (EXAM_ITEM_NAME LIKE N'%内置管%' OR EXAM_CONCLUSION_PLAIN_TEXT LIKE N'%内置管%') THEN EXAM_TASK_ID END) AS 胃内置管, 
    -- 肠镜统计（按照检查项目）
    COUNT(CASE WHEN EXAM_ITEM_NAME LIKE N'%肠镜%' OR EXAM_ITEM_NAME LIKE N'%胃+肠%' OR EXAM_ITEM_NAME LIKE N'%胃肠镜%' THEN EXAM_TASK_ID END) AS 肠镜, 
    -- 无痛肠镜（检查项目）
    COUNT(CASE WHEN (EXAM_ITEM_NAME LIKE N'%无%痛%肠镜%' OR EXAM_ITEM_NAME LIKE N'%无%痛%胃+肠%' OR EXAM_ITEM_NAME LIKE N'%无%痛%胃肠镜%' OR EXAM_ITEM_NAME LIKE N'%无%痛%超声肠镜%') THEN EXAM_TASK_ID END) AS 无痛肠镜, 
    -- 普通肠镜（检查项目）
    COUNT(CASE WHEN ((EXAM_ITEM_NAME LIKE N'%肠镜%' OR EXAM_ITEM_NAME LIKE N'%胃+肠%' OR EXAM_ITEM_NAME LIKE N'%胃肠镜%') AND EXAM_ITEM_NAME NOT LIKE N'%无%痛%') THEN EXAM_TASK_ID END) AS 普通肠镜, 
    -- 肠电切（诊断描述）
    COUNT(CASE WHEN (EXAM_ITEM_NAME LIKE N'%肠镜%' OR EXAM_ITEM_NAME LIKE N'%胃+肠%') AND EXAM_CONCLUSION_PLAIN_TEXT LIKE N'%电切%' THEN EXAM_TASK_ID END) AS 肠电切, 
    -- 肠ESD（诊断描述）
    COUNT(CASE WHEN (EXAM_ITEM_NAME LIKE N'%肠镜%' OR EXAM_ITEM_NAME LIKE N'%胃+肠%') AND EXAM_CONCLUSION_PLAIN_TEXT LIKE N'%ESD%' THEN EXAM_TASK_ID END) AS 肠ESD, 
    -- 肠EMR（诊断描述）
    COUNT(CASE WHEN (EXAM_ITEM_NAME LIKE N'%肠镜%' OR EXAM_ITEM_NAME LIKE N'%胃+肠%') AND EXAM_CONCLUSION_PLAIN_TEXT LIKE N'%EMR%' THEN EXAM_TASK_ID END) AS 肠EMR, 
    -- 超声肠镜
    COUNT(CASE WHEN (EXAM_ITEM_NAME LIKE N'%超声%' OR EXAM_ITEM_NAME LIKE N'%CN%') AND (EXAM_ITEM_NAME LIKE N'%肠%' OR EXAM_CONCLUSION_PLAIN_TEXT LIKE N'%肠%') THEN EXAM_TASK_ID END) AS 超声肠镜, 
    -- 支气管镜
    COUNT(CASE WHEN EXAM_ITEM_NAME LIKE N'%支气管%' OR EXAM_ITEM_NAME LIKE N'%ZQG%' THEN EXAM_TASK_ID END) AS 支气管镜, 
    -- ERCP（检查项目包含ERCP）
    COUNT(CASE WHEN EXAM_ITEM_NAME LIKE N'%ERCP%' OR EXAM_ITEM_NAME LIKE N'%ercp%' OR EXAM_ITEM_NAME LIKE N'%Ercp%' THEN EXAM_TASK_ID END) AS ERCP, 
    -- 横向求和：每个医生的总工作量
    COUNT(EXAM_TASK_ID) AS 总工作量 
FROM TaskData
GROUP BY REPORTER_NAME
UNION ALL
-- 纵向求和：所有医生的汇总数据
SELECT 
    '总计' AS 医生姓名, 
    SUM(CASE WHEN (EXAM_ITEM_NAME LIKE N'%胃镜%' OR EXAM_ITEM_NAME LIKE N'%胃+肠%' OR EXAM_ITEM_NAME LIKE N'%胃肠镜%') AND NOT (EXAM_ITEM_NAME LIKE N'%14碳%') THEN 1 ELSE 0 END) AS 胃镜, 
    SUM(CASE WHEN (EXAM_ITEM_NAME LIKE N'%无%痛%胃镜%' OR EXAM_ITEM_NAME LIKE N'%无%痛%胃+肠%' OR EXAM_ITEM_NAME LIKE N'%无%痛%胃肠镜%' OR EXAM_ITEM_NAME LIKE N'%无%痛%超声胃镜%') AND NOT (EXAM_ITEM_NAME LIKE N'%14碳%') THEN 1 ELSE 0 END) AS 无痛胃镜, 
    SUM(CASE WHEN ((EXAM_ITEM_NAME LIKE N'%胃镜%' OR EXAM_ITEM_NAME LIKE N'%胃+肠%' OR EXAM_ITEM_NAME LIKE N'%胃肠镜%') AND EXAM_ITEM_NAME NOT LIKE N'%无%痛%') AND NOT (EXAM_ITEM_NAME LIKE N'%14碳%') THEN 1 ELSE 0 END) AS 普通胃镜, 
    SUM(CASE WHEN (EXAM_ITEM_NAME LIKE N'%胃镜%' OR EXAM_ITEM_NAME LIKE N'%胃+肠%') AND EXAM_CONCLUSION_PLAIN_TEXT LIKE N'%电切%' THEN 1 ELSE 0 END) AS 胃电切, 
    SUM(CASE WHEN (EXAM_ITEM_NAME LIKE N'%胃镜%' OR EXAM_ITEM_NAME LIKE N'%胃+肠%') AND EXAM_CONCLUSION_PLAIN_TEXT LIKE N'%ESD%' THEN 1 ELSE 0 END) AS 胃ESD, 
    SUM(CASE WHEN (EXAM_ITEM_NAME LIKE N'%胃镜%' OR EXAM_ITEM_NAME LIKE N'%胃+肠%') AND EXAM_CONCLUSION_PLAIN_TEXT LIKE N'%EMR%' THEN 1 ELSE 0 END) AS 胃EMR, 
    SUM(CASE WHEN EXAM_CONCLUSION_PLAIN_TEXT LIKE N'%套扎%' THEN 1 ELSE 0 END) AS 套扎, 
    SUM(CASE WHEN EXAM_CONCLUSION_PLAIN_TEXT LIKE N'%硬化%' THEN 1 ELSE 0 END) AS 硬化, 
    SUM(CASE WHEN EXAM_CONCLUSION_PLAIN_TEXT LIKE N'%支架%' THEN 1 ELSE 0 END) AS 支架, 
    SUM(CASE WHEN EXAM_CONCLUSION_PLAIN_TEXT LIKE N'%异物%' THEN 1 ELSE 0 END) AS 异物, 
    SUM(CASE WHEN (EXAM_ITEM_NAME LIKE N'%超声%' OR EXAM_ITEM_NAME LIKE N'%CN%') AND (EXAM_ITEM_NAME LIKE N'%胃%' OR EXAM_CONCLUSION_PLAIN_TEXT LIKE N'%胃%') THEN 1 ELSE 0 END) AS 超声胃镜, 
    SUM(CASE WHEN (EXAM_ITEM_NAME LIKE N'%超声%' OR EXAM_ITEM_NAME LIKE N'%CN%') AND (EXAM_ITEM_NAME LIKE N'%内置管%' OR EXAM_CONCLUSION_PLAIN_TEXT LIKE N'%内置管%') THEN 1 ELSE 0 END) AS 胃内置管, 
    SUM(CASE WHEN EXAM_ITEM_NAME LIKE N'%肠镜%' OR EXAM_ITEM_NAME LIKE N'%胃+肠%' OR EXAM_ITEM_NAME LIKE N'%胃肠镜%' THEN 1 ELSE 0 END) AS 肠镜, 
    SUM(CASE WHEN (EXAM_ITEM_NAME LIKE N'%无%痛%肠镜%' OR EXAM_ITEM_NAME LIKE N'%无%痛%胃+肠%' OR EXAM_ITEM_NAME LIKE N'%无%痛%胃肠镜%' OR EXAM_ITEM_NAME LIKE N'%无%痛%超声肠镜%') THEN 1 ELSE 0 END) AS 无痛肠镜, 
    SUM(CASE WHEN ((EXAM_ITEM_NAME LIKE N'%肠镜%' OR EXAM_ITEM_NAME LIKE N'%胃+肠%' OR EXAM_ITEM_NAME LIKE N'%胃肠镜%') AND EXAM_ITEM_NAME NOT LIKE N'%无%痛%') THEN 1 ELSE 0 END) AS 普通肠镜, 
    SUM(CASE WHEN (EXAM_ITEM_NAME LIKE N'%肠镜%' OR EXAM_ITEM_NAME LIKE N'%胃+肠%') AND EXAM_CONCLUSION_PLAIN_TEXT LIKE N'%电切%' THEN 1 ELSE 0 END) AS 肠电切, 
    SUM(CASE WHEN (EXAM_ITEM_NAME LIKE N'%肠镜%' OR EXAM_ITEM_NAME LIKE N'%胃+肠%') AND EXAM_CONCLUSION_PLAIN_TEXT LIKE N'%ESD%' THEN 1 ELSE 0 END) AS 肠ESD, 
    SUM(CASE WHEN (EXAM_ITEM_NAME LIKE N'%肠镜%' OR EXAM_ITEM_NAME LIKE N'%胃+肠%') AND EXAM_CONCLUSION_PLAIN_TEXT LIKE N'%EMR%' THEN 1 ELSE 0 END) AS 肠EMR, 
    SUM(CASE WHEN (EXAM_ITEM_NAME LIKE N'%超声%' OR EXAM_ITEM_NAME LIKE N'%CN%') AND (EXAM_ITEM_NAME LIKE N'%肠%' OR EXAM_CONCLUSION_PLAIN_TEXT LIKE N'%肠%') THEN 1 ELSE 0 END) AS 超声肠镜, 
    SUM(CASE WHEN EXAM_ITEM_NAME LIKE N'%支气管%' OR EXAM_ITEM_NAME LIKE N'%ZQG%' THEN 1 ELSE 0 END) AS 支气管镜, 
    SUM(CASE WHEN EXAM_ITEM_NAME LIKE N'%ERCP%' OR EXAM_ITEM_NAME LIKE N'%ercp%' OR EXAM_ITEM_NAME LIKE N'%Ercp%' THEN 1 ELSE 0 END) AS ERCP, 
    COUNT(*) AS 总工作量 
FROM TaskData
ORDER BY 
    CASE WHEN REPORTER_NAME = '总计' THEN 1 ELSE 0 END, 
    REPORTER_NAME;