-- 放射科（RIS）工作量统计SQL查询
-- 统计日期：2026年4月1日
-- 统计类型：报告医生、审核医生、技师工作量
-- 基于实际数据库结构编写

USE WiNEX_PACS;

-- 定义日期变量
DECLARE @StartDate DATETIME = '2026-04-01 00:00:00';
DECLARE @EndDate DATETIME = '2026-04-01 23:59:59';

-- 1. 查询各检查类别的数量（验证用）
PRINT '=== 各检查类别数量 ===';
SELECT 
    t.EXAM_CATEGORY_NAME AS 检查类别,
    COUNT(DISTINCT t.EXAM_TASK_ID) AS 数量
FROM EXAM_TASK t
INNER JOIN EXAM_REPORT r ON t.EXAM_TASK_ID = r.EXAM_TASK_ID AND t.IS_DEL = 0
WHERE t.IS_DEL = 0
  AND r.IS_DEL = 0
  AND t.SYSTEM_SOURCE_NO = 'RIS'
  AND t.EXAM_TASK_STATUS >= 50
  AND t.CREATED_AT >= @StartDate
  AND t.CREATED_AT <= @EndDate
GROUP BY t.EXAM_CATEGORY_NAME
ORDER BY 数量 DESC;

-- 2. 报告医生工作量统计
PRINT '';
PRINT '=== 报告医生工作量统计 ===';
WITH TaskData AS (
    SELECT DISTINCT
        r.REPORTER_NAME AS DoctorName,
        t.EXAM_TASK_ID,
        t.EXAM_CATEGORY_NAME
    FROM EXAM_REPORT r
    INNER JOIN EXAM_TASK t ON r.EXAM_TASK_ID = t.EXAM_TASK_ID AND t.IS_DEL = 0
    WHERE r.IS_DEL = 0
      AND t.SYSTEM_SOURCE_NO = 'RIS'
      AND t.EXAM_TASK_STATUS >= 50
      AND t.CREATED_AT >= @StartDate
      AND t.CREATED_AT <= @EndDate
      AND r.REPORTER_NAME IS NOT NULL
    GROUP BY r.REPORTER_NAME, t.EXAM_TASK_ID, t.EXAM_CATEGORY_NAME
)
SELECT 
    DoctorName AS 医生姓名, 
    SUM(CASE WHEN EXAM_CATEGORY_NAME IN (N'普放', N'普放(新)') THEN 1 ELSE 0 END) AS DR,
    SUM(CASE WHEN EXAM_CATEGORY_NAME = N'钼靶' THEN 1 ELSE 0 END) AS 钼靶,
    SUM(CASE WHEN EXAM_CATEGORY_NAME IN (N'消化道造影', N'消化道造影(新)') THEN 1 ELSE 0 END) AS 造影,
    SUM(CASE WHEN EXAM_CATEGORY_NAME IN (N'普放', N'普放(新)', N'钼靶', N'消化道造影', N'消化道造影(新)') THEN 1 ELSE 0 END) AS 普放组,
    SUM(CASE WHEN EXAM_CATEGORY_NAME = N'CT' THEN 1 ELSE 0 END) AS CT平扫,
    SUM(CASE WHEN EXAM_CATEGORY_NAME = N'CT(新)' THEN 1 ELSE 0 END) AS CT增强,
    SUM(CASE WHEN EXAM_CATEGORY_NAME IN (N'CTA', N'CTA(新)') THEN 1 ELSE 0 END) AS CCTA,
    SUM(CASE WHEN EXAM_CATEGORY_NAME IN (N'CT重建', N'CT三维重建') THEN 1 ELSE 0 END) AS CT重建,
    SUM(CASE WHEN EXAM_CATEGORY_NAME IN (N'CT', N'CT(新)', N'CTA', N'CTA(新)', N'CT重建', N'CT三维重建') THEN 1 ELSE 0 END) AS CT组,
    SUM(CASE WHEN EXAM_CATEGORY_NAME = N'核磁共振' THEN 1 ELSE 0 END) AS MRI平扫,
    SUM(CASE WHEN EXAM_CATEGORY_NAME IN (N'核磁共振增强', N'MRI增强') THEN 1 ELSE 0 END) AS MRI增强,
    SUM(CASE WHEN EXAM_CATEGORY_NAME = N'MRA' THEN 1 ELSE 0 END) AS MRA,
    SUM(CASE WHEN EXAM_CATEGORY_NAME = N'MRV' THEN 1 ELSE 0 END) AS MRV,
    SUM(CASE WHEN EXAM_CATEGORY_NAME = N'MRU' THEN 1 ELSE 0 END) AS MRU,
    SUM(CASE WHEN EXAM_CATEGORY_NAME = N'MRCP' THEN 1 ELSE 0 END) AS MRCP,
    SUM(CASE WHEN EXAM_CATEGORY_NAME = N'MRS' THEN 1 ELSE 0 END) AS MRS,
    SUM(CASE WHEN EXAM_CATEGORY_NAME IN (N'核磁共振', N'核磁共振增强', N'MRI增强', N'MRA', N'MRV', N'MRU', N'MRCP', N'MRS') THEN 1 ELSE 0 END) AS MRI组,
    COUNT(EXAM_TASK_ID) AS 总工作量 
FROM TaskData
GROUP BY DoctorName
ORDER BY 总工作量 DESC;

-- 3. 审核医生工作量统计
PRINT '';
PRINT '=== 审核医生工作量统计 ===';
WITH TaskData AS (
    SELECT DISTINCT
        r.REVIEWER_NAME AS DoctorName,
        t.EXAM_TASK_ID,
        t.EXAM_CATEGORY_NAME
    FROM EXAM_REPORT r
    INNER JOIN EXAM_TASK t ON r.EXAM_TASK_ID = t.EXAM_TASK_ID AND t.IS_DEL = 0
    WHERE r.IS_DEL = 0
      AND t.SYSTEM_SOURCE_NO = 'RIS'
      AND t.EXAM_TASK_STATUS >= 50
      AND t.CREATED_AT >= @StartDate
      AND t.CREATED_AT <= @EndDate
      AND r.REVIEWER_NAME IS NOT NULL
    GROUP BY r.REVIEWER_NAME, t.EXAM_TASK_ID, t.EXAM_CATEGORY_NAME
)
SELECT 
    DoctorName AS 医生姓名, 
    SUM(CASE WHEN EXAM_CATEGORY_NAME IN (N'普放', N'普放(新)') THEN 1 ELSE 0 END) AS DR,
    SUM(CASE WHEN EXAM_CATEGORY_NAME = N'钼靶' THEN 1 ELSE 0 END) AS 钼靶,
    SUM(CASE WHEN EXAM_CATEGORY_NAME IN (N'消化道造影', N'消化道造影(新)') THEN 1 ELSE 0 END) AS 造影,
    SUM(CASE WHEN EXAM_CATEGORY_NAME IN (N'普放', N'普放(新)', N'钼靶', N'消化道造影', N'消化道造影(新)') THEN 1 ELSE 0 END) AS 普放组,
    SUM(CASE WHEN EXAM_CATEGORY_NAME = N'CT' THEN 1 ELSE 0 END) AS CT平扫,
    SUM(CASE WHEN EXAM_CATEGORY_NAME = N'CT(新)' THEN 1 ELSE 0 END) AS CT增强,
    SUM(CASE WHEN EXAM_CATEGORY_NAME IN (N'CTA', N'CTA(新)') THEN 1 ELSE 0 END) AS CCTA,
    SUM(CASE WHEN EXAM_CATEGORY_NAME IN (N'CT重建', N'CT三维重建') THEN 1 ELSE 0 END) AS CT重建,
    SUM(CASE WHEN EXAM_CATEGORY_NAME IN (N'CT', N'CT(新)', N'CTA', N'CTA(新)', N'CT重建', N'CT三维重建') THEN 1 ELSE 0 END) AS CT组,
    SUM(CASE WHEN EXAM_CATEGORY_NAME = N'核磁共振' THEN 1 ELSE 0 END) AS MRI平扫,
    SUM(CASE WHEN EXAM_CATEGORY_NAME IN (N'核磁共振增强', N'MRI增强') THEN 1 ELSE 0 END) AS MRI增强,
    SUM(CASE WHEN EXAM_CATEGORY_NAME = N'MRA' THEN 1 ELSE 0 END) AS MRA,
    SUM(CASE WHEN EXAM_CATEGORY_NAME = N'MRV' THEN 1 ELSE 0 END) AS MRV,
    SUM(CASE WHEN EXAM_CATEGORY_NAME = N'MRU' THEN 1 ELSE 0 END) AS MRU,
    SUM(CASE WHEN EXAM_CATEGORY_NAME = N'MRCP' THEN 1 ELSE 0 END) AS MRCP,
    SUM(CASE WHEN EXAM_CATEGORY_NAME = N'MRS' THEN 1 ELSE 0 END) AS MRS,
    SUM(CASE WHEN EXAM_CATEGORY_NAME IN (N'核磁共振', N'核磁共振增强', N'MRI增强', N'MRA', N'MRV', N'MRU', N'MRCP', N'MRS') THEN 1 ELSE 0 END) AS MRI组,
    COUNT(EXAM_TASK_ID) AS 总工作量 
FROM TaskData
GROUP BY DoctorName
ORDER BY 总工作量 DESC;

-- 4. 技师工作量统计
PRINT '';
PRINT '=== 技师工作量统计 ===';
WITH TaskData AS (
    SELECT DISTINCT
        t.TECHNICIAN_NAME AS DoctorName,
        t.EXAM_TASK_ID,
        t.EXAM_CATEGORY_NAME
    FROM EXAM_TASK t
    INNER JOIN EXAM_REPORT r ON t.EXAM_TASK_ID = r.EXAM_TASK_ID AND t.IS_DEL = 0
    WHERE t.IS_DEL = 0
      AND r.IS_DEL = 0
      AND t.SYSTEM_SOURCE_NO = 'RIS'
      AND t.EXAM_TASK_STATUS >= 50
      AND t.CREATED_AT >= @StartDate
      AND t.CREATED_AT <= @EndDate
      AND t.TECHNICIAN_NAME IS NOT NULL
    GROUP BY t.TECHNICIAN_NAME, t.EXAM_TASK_ID, t.EXAM_CATEGORY_NAME
)
SELECT 
    DoctorName AS 技师姓名, 
    SUM(CASE WHEN EXAM_CATEGORY_NAME IN (N'普放', N'普放(新)') THEN 1 ELSE 0 END) AS DR,
    SUM(CASE WHEN EXAM_CATEGORY_NAME = N'钼靶' THEN 1 ELSE 0 END) AS 钼靶,
    SUM(CASE WHEN EXAM_CATEGORY_NAME IN (N'消化道造影', N'消化道造影(新)') THEN 1 ELSE 0 END) AS 造影,
    SUM(CASE WHEN EXAM_CATEGORY_NAME IN (N'普放', N'普放(新)', N'钼靶', N'消化道造影', N'消化道造影(新)') THEN 1 ELSE 0 END) AS 普放组,
    SUM(CASE WHEN EXAM_CATEGORY_NAME = N'CT' THEN 1 ELSE 0 END) AS CT平扫,
    SUM(CASE WHEN EXAM_CATEGORY_NAME = N'CT(新)' THEN 1 ELSE 0 END) AS CT增强,
    SUM(CASE WHEN EXAM_CATEGORY_NAME IN (N'CT', N'CT(新)', N'CTA', N'CCTA', N'CT重建') THEN 1 ELSE 0 END) AS CT组,
    SUM(CASE WHEN EXAM_CATEGORY_NAME = N'核磁共振' THEN 1 ELSE 0 END) AS MRI平扫,
    SUM(CASE WHEN EXAM_CATEGORY_NAME IN (N'核磁共振', N'核磁共振增强') THEN 1 ELSE 0 END) AS MRI组,
    COUNT(EXAM_TASK_ID) AS 总工作量 
FROM TaskData
GROUP BY DoctorName
ORDER BY 总工作量 DESC;

-- 5. 总计统计
PRINT '';
PRINT '=== 总计统计 ===';
WITH TaskData AS (
    SELECT DISTINCT
        t.EXAM_TASK_ID,
        t.EXAM_CATEGORY_NAME
    FROM EXAM_TASK t
    INNER JOIN EXAM_REPORT r ON t.EXAM_TASK_ID = r.EXAM_TASK_ID AND t.IS_DEL = 0
    WHERE t.IS_DEL = 0
      AND r.IS_DEL = 0
      AND t.SYSTEM_SOURCE_NO = 'RIS'
      AND t.EXAM_TASK_STATUS >= 50
      AND t.CREATED_AT >= @StartDate
      AND t.CREATED_AT <= @EndDate
    GROUP BY t.EXAM_TASK_ID, t.EXAM_CATEGORY_NAME
)
SELECT 
    '总计' AS 项目, 
    SUM(CASE WHEN EXAM_CATEGORY_NAME IN (N'普放', N'普放(新)') THEN 1 ELSE 0 END) AS DR,
    SUM(CASE WHEN EXAM_CATEGORY_NAME = N'钼靶' THEN 1 ELSE 0 END) AS 钼靶,
    SUM(CASE WHEN EXAM_CATEGORY_NAME IN (N'消化道造影', N'消化道造影(新)') THEN 1 ELSE 0 END) AS 造影,
    SUM(CASE WHEN EXAM_CATEGORY_NAME IN (N'普放', N'普放(新)', N'钼靶', N'消化道造影', N'消化道造影(新)') THEN 1 ELSE 0 END) AS 普放组,
    SUM(CASE WHEN EXAM_CATEGORY_NAME = N'CT' THEN 1 ELSE 0 END) AS CT平扫,
    SUM(CASE WHEN EXAM_CATEGORY_NAME = N'CT(新)' THEN 1 ELSE 0 END) AS CT增强,
    SUM(CASE WHEN EXAM_CATEGORY_NAME IN (N'CTA', N'CTA(新)') THEN 1 ELSE 0 END) AS CCTA,
    SUM(CASE WHEN EXAM_CATEGORY_NAME IN (N'CT重建', N'CT三维重建') THEN 1 ELSE 0 END) AS CT重建,
    SUM(CASE WHEN EXAM_CATEGORY_NAME IN (N'CT', N'CT(新)', N'CTA', N'CTA(新)', N'CT重建', N'CT三维重建') THEN 1 ELSE 0 END) AS CT组,
    SUM(CASE WHEN EXAM_CATEGORY_NAME = N'核磁共振' THEN 1 ELSE 0 END) AS MRI平扫,
    SUM(CASE WHEN EXAM_CATEGORY_NAME IN (N'核磁共振增强', N'MRI增强') THEN 1 ELSE 0 END) AS MRI增强,
    SUM(CASE WHEN EXAM_CATEGORY_NAME = N'MRA' THEN 1 ELSE 0 END) AS MRA,
    SUM(CASE WHEN EXAM_CATEGORY_NAME = N'MRV' THEN 1 ELSE 0 END) AS MRV,
    SUM(CASE WHEN EXAM_CATEGORY_NAME = N'MRU' THEN 1 ELSE 0 END) AS MRU,
    SUM(CASE WHEN EXAM_CATEGORY_NAME = N'MRCP' THEN 1 ELSE 0 END) AS MRCP,
    SUM(CASE WHEN EXAM_CATEGORY_NAME = N'MRS' THEN 1 ELSE 0 END) AS MRS,
    SUM(CASE WHEN EXAM_CATEGORY_NAME IN (N'核磁共振', N'核磁共振增强', N'MRI增强', N'MRA', N'MRV', N'MRU', N'MRCP', N'MRS') THEN 1 ELSE 0 END) AS MRI组,
    COUNT(*) AS 总工作量,
    SUM(CASE WHEN EXAM_CATEGORY_NAME IN (N'普放', N'普放(新)', N'钼靶', N'消化道造影', N'消化道造影(新)', N'CT', N'CT(新)', N'CTA', N'CTA(新)', N'CT重建', N'CT三维重建', N'核磁共振', N'核磁共振增强', N'MRI增强', N'MRA', N'MRV', N'MRU', N'MRCP', N'MRS') THEN 1 ELSE 0 END) AS 分组总计
FROM TaskData;