-- 查询 EXAM_TASK 表中与 ENCOUNTER 相关的字段
SELECT
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EXAM_TASK'
    AND COLUMN_NAME LIKE '%ENCOUNTER%'
ORDER BY ORDINAL_POSITION;

-- 查询表的所有列名
SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EXAM_TASK'
ORDER BY ORDINAL_POSITION;
