-- 放射科（RIS）工作量统计存储过程
-- 版本：v1.7
-- 日期：2026-04-24
-- 功能：统计放射科工作量，支持报告医生、审核医生、技师三种统计类型
-- 基于Schema文档优化，使用正确的字段名

IF OBJECT_ID('sp_RadiologyWorkloadStatistics', 'P') IS NOT NULL
    DROP PROCEDURE sp_RadiologyWorkloadStatistics;
GO

CREATE PROCEDURE sp_RadiologyWorkloadStatistics
    @StartDate DATETIME,
    @EndDate DATETIME,
    @StatisticsType VARCHAR(20) = 'reporter'
AS
BEGIN
    SET NOCOUNT ON;

    IF @StatisticsType = 'reporter'
    BEGIN
        SELECT 
            r.REPORTER_NAME AS 医生姓名, 
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME IN (N'普放', N'普放(新)') THEN 1 ELSE 0 END) AS DR,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME = N'钼靶' THEN 1 ELSE 0 END) AS 钼靶,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME IN (N'消化道造影', N'消化道造影(新)') THEN 1 ELSE 0 END) AS 造影,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME IN (N'普放', N'普放(新)', N'钼靶', N'消化道造影', N'消化道造影(新)') THEN 1 ELSE 0 END) AS 普放组,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME = N'CT' THEN 1 ELSE 0 END) AS CT平扫,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME = N'CT(新)' THEN 1 ELSE 0 END) AS CT增强,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'%CTA%' THEN 1 ELSE 0 END) AS CCTA,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'%重建%' THEN 1 ELSE 0 END) AS CT重建,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'CT%' THEN 1 ELSE 0 END) AS CT组,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME = N'核磁共振' THEN 1 ELSE 0 END) AS MRI平扫,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME IN (N'核磁共振增强', N'MRI增强') THEN 1 ELSE 0 END) AS MRI增强,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME = N'MRA' THEN 1 ELSE 0 END) AS MRA,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME = N'MRV' THEN 1 ELSE 0 END) AS MRV,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME = N'MRU' THEN 1 ELSE 0 END) AS MRU,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME = N'MRCP' THEN 1 ELSE 0 END) AS MRCP,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME = N'MRS' THEN 1 ELSE 0 END) AS MRS,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'%乳腺%' THEN 1 ELSE 0 END) AS 乳腺,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'%心脏%' THEN 1 ELSE 0 END) AS 心脏,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'%腹部%' THEN 1 ELSE 0 END) AS 腹部,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'%盆腔%' THEN 1 ELSE 0 END) AS 盆腔,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'%前列腺%' THEN 1 ELSE 0 END) AS 前列腺,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'%直肠%' THEN 1 ELSE 0 END) AS 直肠,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'%胎儿%' THEN 1 ELSE 0 END) AS 胎儿,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'%胎盘%' THEN 1 ELSE 0 END) AS 胎盘,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME IN (N'核磁共振', N'核磁共振增强', N'MRI增强', N'MRA', N'MRV', N'MRU', N'MRCP', N'MRS') THEN 1 ELSE 0 END) AS MRI组,
            COUNT(DISTINCT t.EXAM_TASK_ID) AS 总工作量 
        FROM EXAM_REPORT r
        INNER JOIN EXAM_TASK t ON r.EXAM_TASK_ID = t.EXAM_TASK_ID AND t.IS_DEL = 0
        WHERE r.IS_DEL = 0
          AND t.SYSTEM_SOURCE_NO = 'RIS'
          AND t.EXAM_TASK_STATUS >= 50
          AND t.REGISTER_AT >= @StartDate
          AND t.REGISTER_AT <= @EndDate
          AND r.REPORTER_NAME IS NOT NULL
        GROUP BY r.REPORTER_NAME
        ORDER BY 总工作量 DESC;
    END
    ELSE IF @StatisticsType = 'reviewer'
    BEGIN
        SELECT 
            r.REVIEWER_NAME AS 医生姓名, 
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME IN (N'普放', N'普放(新)') THEN 1 ELSE 0 END) AS DR,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME = N'钼靶' THEN 1 ELSE 0 END) AS 钼靶,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME IN (N'消化道造影', N'消化道造影(新)') THEN 1 ELSE 0 END) AS 造影,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME IN (N'普放', N'普放(新)', N'钼靶', N'消化道造影', N'消化道造影(新)') THEN 1 ELSE 0 END) AS 普放组,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME = N'CT' THEN 1 ELSE 0 END) AS CT平扫,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME = N'CT(新)' THEN 1 ELSE 0 END) AS CT增强,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'%CTA%' THEN 1 ELSE 0 END) AS CCTA,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'%重建%' THEN 1 ELSE 0 END) AS CT重建,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'CT%' THEN 1 ELSE 0 END) AS CT组,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME = N'核磁共振' THEN 1 ELSE 0 END) AS MRI平扫,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME IN (N'核磁共振增强', N'MRI增强') THEN 1 ELSE 0 END) AS MRI增强,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME = N'MRA' THEN 1 ELSE 0 END) AS MRA,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME = N'MRV' THEN 1 ELSE 0 END) AS MRV,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME = N'MRU' THEN 1 ELSE 0 END) AS MRU,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME = N'MRCP' THEN 1 ELSE 0 END) AS MRCP,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME = N'MRS' THEN 1 ELSE 0 END) AS MRS,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'%乳腺%' THEN 1 ELSE 0 END) AS 乳腺,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'%心脏%' THEN 1 ELSE 0 END) AS 心脏,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'%腹部%' THEN 1 ELSE 0 END) AS 腹部,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'%盆腔%' THEN 1 ELSE 0 END) AS 盆腔,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'%前列腺%' THEN 1 ELSE 0 END) AS 前列腺,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'%直肠%' THEN 1 ELSE 0 END) AS 直肠,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'%胎儿%' THEN 1 ELSE 0 END) AS 胎儿,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'%胎盘%' THEN 1 ELSE 0 END) AS 胎盘,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME IN (N'核磁共振', N'核磁共振增强', N'MRI增强', N'MRA', N'MRV', N'MRU', N'MRCP', N'MRS') THEN 1 ELSE 0 END) AS MRI组,
            COUNT(DISTINCT t.EXAM_TASK_ID) AS 总工作量 
        FROM EXAM_REPORT r
        INNER JOIN EXAM_TASK t ON r.EXAM_TASK_ID = t.EXAM_TASK_ID AND t.IS_DEL = 0
        WHERE r.IS_DEL = 0
          AND t.SYSTEM_SOURCE_NO = 'RIS'
          AND t.EXAM_TASK_STATUS >= 50
          AND t.REGISTER_AT >= @StartDate
          AND t.REGISTER_AT <= @EndDate
          AND r.REVIEWER_NAME IS NOT NULL
        GROUP BY r.REVIEWER_NAME
        ORDER BY 总工作量 DESC;
    END
    ELSE IF @StatisticsType = 'technician'
    BEGIN
        SELECT 
            t.TECHNICIAN_NAME AS 技师姓名, 
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME IN (N'普放', N'普放(新)') THEN 1 ELSE 0 END) AS DR,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME = N'钼靶' THEN 1 ELSE 0 END) AS 钼靶,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME IN (N'消化道造影', N'消化道造影(新)') THEN 1 ELSE 0 END) AS 造影,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME IN (N'普放', N'普放(新)', N'钼靶', N'消化道造影', N'消化道造影(新)') THEN 1 ELSE 0 END) AS 普放组,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME = N'CT' THEN 1 ELSE 0 END) AS CT平扫,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME = N'CT(新)' THEN 1 ELSE 0 END) AS CT增强,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'%CTA%' THEN 1 ELSE 0 END) AS CCTA,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'%重建%' THEN 1 ELSE 0 END) AS CT重建,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'CT%' THEN 1 ELSE 0 END) AS CT组,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME = N'核磁共振' THEN 1 ELSE 0 END) AS MRI平扫,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME IN (N'核磁共振增强', N'MRI增强') THEN 1 ELSE 0 END) AS MRI增强,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME = N'MRA' THEN 1 ELSE 0 END) AS MRA,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME = N'MRV' THEN 1 ELSE 0 END) AS MRV,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME = N'MRU' THEN 1 ELSE 0 END) AS MRU,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME = N'MRCP' THEN 1 ELSE 0 END) AS MRCP,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME = N'MRS' THEN 1 ELSE 0 END) AS MRS,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'%乳腺%' THEN 1 ELSE 0 END) AS 乳腺,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'%心脏%' THEN 1 ELSE 0 END) AS 心脏,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'%腹部%' THEN 1 ELSE 0 END) AS 腹部,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'%盆腔%' THEN 1 ELSE 0 END) AS 盆腔,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'%前列腺%' THEN 1 ELSE 0 END) AS 前列腺,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'%直肠%' THEN 1 ELSE 0 END) AS 直肠,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'%胎儿%' THEN 1 ELSE 0 END) AS 胎儿,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME LIKE N'%胎盘%' THEN 1 ELSE 0 END) AS 胎盘,
            SUM(CASE WHEN t.EXAM_CATEGORY_NAME IN (N'核磁共振', N'核磁共振增强', N'MRI增强', N'MRA', N'MRV', N'MRU', N'MRCP', N'MRS') THEN 1 ELSE 0 END) AS MRI组,
            COUNT(DISTINCT t.EXAM_TASK_ID) AS 总工作量 
        FROM EXAM_TASK t
        INNER JOIN EXAM_REPORT r ON t.EXAM_TASK_ID = r.EXAM_TASK_ID AND t.IS_DEL = 0
        WHERE t.IS_DEL = 0
          AND r.IS_DEL = 0
          AND t.SYSTEM_SOURCE_NO = 'RIS'
          AND t.EXAM_TASK_STATUS >= 50
          AND t.REGISTER_AT >= @StartDate
          AND t.REGISTER_AT <= @EndDate
          AND t.TECHNICIAN_NAME IS NOT NULL
        GROUP BY t.TECHNICIAN_NAME
        ORDER BY 总工作量 DESC;
    END

    SET NOCOUNT OFF;
END;
GO
