-- =====================================================
-- 动态查询配置表 - 驱动界面查询条件自动生成
-- =====================================================

CREATE TABLE tjfx_QUERY_CONFIG (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    FIELD_NAME NVARCHAR(50) NOT NULL,
    DISPLAY_NAME NVARCHAR(100) NOT NULL,
    QUERY_SQL NVARCHAR(MAX),
    IS_VISIBLE BIT DEFAULT 1,
    IS_MULTIPLE BIT DEFAULT 0,
    SORT_ORDER INT DEFAULT 0,
    PARENT_FIELD NVARCHAR(50),
    DEFAULT_VALUE NVARCHAR(200),
    PLACEHOLDER NVARCHAR(100),
    IS_ACTIVE BIT DEFAULT 1,
    CREATE_TIME DATETIME DEFAULT GETDATE(),
    UPDATE_TIME DATETIME DEFAULT GETDATE()
);

CREATE UNIQUE INDEX UX_QUERY_FIELD_NAME ON tjfx_QUERY_CONFIG (FIELD_NAME);

-- =====================================================
-- 安全白名单表 - 防止SQL注入
-- =====================================================

CREATE TABLE tjfx_QUERY_WHITELIST (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    FIELD_NAME NVARCHAR(50) NOT NULL,
    ALLOWED_SQL NVARCHAR(MAX) NOT NULL,
    DESCRIPTION NVARCHAR(200),
    IS_ACTIVE BIT DEFAULT 1,
    CREATE_TIME DATETIME DEFAULT GETDATE()
);

-- =====================================================
-- 初始化配置数据
-- =====================================================

INSERT INTO tjfx_QUERY_CONFIG (FIELD_NAME, DISPLAY_NAME, QUERY_SQL, IS_VISIBLE, IS_MULTIPLE, SORT_ORDER, PARENT_FIELD, PLACEHOLDER)
VALUES ('system', '系统', 'SELECT DISTINCT SYSTEM_SOURCE_NO as code, SYSTEM_SOURCE_NO as name FROM EXAM_TASK WHERE SYSTEM_SOURCE_NO IS NOT NULL ORDER BY SYSTEM_SOURCE_NO', 1, 0, 1, NULL, '请选择系统');

INSERT INTO tjfx_QUERY_CONFIG (FIELD_NAME, DISPLAY_NAME, QUERY_SQL, IS_VISIBLE, IS_MULTIPLE, SORT_ORDER, PARENT_FIELD, PLACEHOLDER)
VALUES ('reporter', '报告医生', 'SELECT DISTINCT r.REPORTER_NAME as code, r.REPORTER_NAME as name FROM EXAM_REPORT r INNER JOIN EXAM_TASK t ON r.EXAM_TASK_ID = t.EXAM_TASK_ID WHERE r.REPORTER_NAME IS NOT NULL AND (@PARENT_VALUE = '''' OR t.SYSTEM_SOURCE_NO = @PARENT_VALUE) ORDER BY r.REPORTER_NAME', 1, 1, 2, 'system', '请选择报告医生');

INSERT INTO tjfx_QUERY_CONFIG (FIELD_NAME, DISPLAY_NAME, QUERY_SQL, IS_VISIBLE, IS_MULTIPLE, SORT_ORDER, PARENT_FIELD, PLACEHOLDER)
VALUES ('reviewer', '审核医生', 'SELECT DISTINCT r.REVIEWER_NAME as code, r.REVIEWER_NAME as name FROM EXAM_REPORT r INNER JOIN EXAM_TASK t ON r.EXAM_TASK_ID = t.EXAM_TASK_ID WHERE r.REVIEWER_NAME IS NOT NULL AND (@PARENT_VALUE = '''' OR t.SYSTEM_SOURCE_NO = @PARENT_VALUE) ORDER BY r.REVIEWER_NAME', 1, 1, 3, 'system', '请选择审核医生');

INSERT INTO tjfx_QUERY_CONFIG (FIELD_NAME, DISPLAY_NAME, QUERY_SQL, IS_VISIBLE, IS_MULTIPLE, SORT_ORDER, PARENT_FIELD, PLACEHOLDER)
VALUES ('technician', '技师', 'SELECT DISTINCT t.TECHNICIAN_NAME as code, t.TECHNICIAN_NAME as name FROM EXAM_TASK t WHERE t.TECHNICIAN_NAME IS NOT NULL AND (@PARENT_VALUE = '''' OR t.SYSTEM_SOURCE_NO = @PARENT_VALUE) ORDER BY t.TECHNICIAN_NAME', 1, 1, 4, 'system', '请选择技师');

INSERT INTO tjfx_QUERY_CONFIG (FIELD_NAME, DISPLAY_NAME, QUERY_SQL, IS_VISIBLE, IS_MULTIPLE, SORT_ORDER, PARENT_FIELD, PLACEHOLDER)
VALUES ('department', '执行科室', 'SELECT DISTINCT t.EXEC_DEPT_NAME as code, t.EXEC_DEPT_NAME as name FROM EXAM_TASK t WHERE t.EXEC_DEPT_NAME IS NOT NULL AND (@PARENT_VALUE = '''' OR t.SYSTEM_SOURCE_NO = @PARENT_VALUE) ORDER BY t.EXEC_DEPT_NAME', 1, 1, 5, 'system', '请选择执行科室');

INSERT INTO tjfx_QUERY_CONFIG (FIELD_NAME, DISPLAY_NAME, QUERY_SQL, IS_VISIBLE, IS_MULTIPLE, SORT_ORDER, PARENT_FIELD, PLACEHOLDER)
VALUES ('category', '检查类型', 'SELECT DISTINCT t.EXAM_CATEGORY_NAME as code, t.EXAM_CATEGORY_NAME as name FROM EXAM_TASK t WHERE t.EXAM_CATEGORY_NAME IS NOT NULL AND (@PARENT_VALUE = '''' OR t.SYSTEM_SOURCE_NO = @PARENT_VALUE) ORDER BY t.EXAM_CATEGORY_NAME', 1, 1, 6, 'system', '请选择检查类型');

INSERT INTO tjfx_QUERY_CONFIG (FIELD_NAME, DISPLAY_NAME, QUERY_SQL, IS_VISIBLE, IS_MULTIPLE, SORT_ORDER, PARENT_FIELD, PLACEHOLDER)
VALUES ('patientType', '病人类型', 'SELECT DISTINCT t.ENCOUNTER_TYPE_NAME as code, t.ENCOUNTER_TYPE_NAME as name FROM EXAM_TASK t WHERE t.ENCOUNTER_TYPE_NAME IS NOT NULL AND (@PARENT_VALUE = '''' OR t.SYSTEM_SOURCE_NO = @PARENT_VALUE) ORDER BY t.ENCOUNTER_TYPE_NAME', 1, 1, 7, 'system', '请选择病人类型');

INSERT INTO tjfx_QUERY_CONFIG (FIELD_NAME, DISPLAY_NAME, QUERY_SQL, IS_VISIBLE, IS_MULTIPLE, SORT_ORDER, PARENT_FIELD, PLACEHOLDER)
VALUES ('resultStatus', '结果状态', 'SELECT DISTINCT REPORT_RESULT_STATUS as code, REPORT_RESULT_STATUS as name FROM EXAM_REPORT WHERE REPORT_RESULT_STATUS IS NOT NULL ORDER BY REPORT_RESULT_STATUS', 1, 1, 8, NULL, '请选择结果状态');

GO

INSERT INTO tjfx_QUERY_WHITELIST (FIELD_NAME, ALLOWED_SQL, DESCRIPTION) VALUES  
('system', 'SELECT DISTINCT SYSTEM_SOURCE_NO as code, SYSTEM_SOURCE_NO as name FROM EXAM_TASK WHERE SYSTEM_SOURCE_NO IS NOT NULL ORDER BY SYSTEM_SOURCE_NO', '获取系统列表'),
('reporter', 'SELECT DISTINCT r.REPORTER_NAME as code, r.REPORTER_NAME as name FROM EXAM_REPORT r INNER JOIN EXAM_TASK t ON r.EXAM_TASK_ID = t.EXAM_TASK_ID WHERE r.REPORTER_NAME IS NOT NULL AND (@PARENT_VALUE = '''' OR t.SYSTEM_SOURCE_NO = @PARENT_VALUE) ORDER BY r.REPORTER_NAME', '获取报告医生列表'),
('reviewer', 'SELECT DISTINCT r.REVIEWER_NAME as code, r.REVIEWER_NAME as name FROM EXAM_REPORT r INNER JOIN EXAM_TASK t ON r.EXAM_TASK_ID = t.EXAM_TASK_ID WHERE r.REVIEWER_NAME IS NOT NULL AND (@PARENT_VALUE = '''' OR t.SYSTEM_SOURCE_NO = @PARENT_VALUE) ORDER BY r.REVIEWER_NAME', '获取审核医生列表'),
('technician', 'SELECT DISTINCT t.TECHNICIAN_NAME as code, t.TECHNICIAN_NAME as name FROM EXAM_TASK t WHERE t.TECHNICIAN_NAME IS NOT NULL AND (@PARENT_VALUE = '''' OR t.SYSTEM_SOURCE_NO = @PARENT_VALUE) ORDER BY t.TECHNICIAN_NAME', '获取技师列表'),
('department', 'SELECT DISTINCT t.EXEC_DEPT_NAME as code, t.EXEC_DEPT_NAME as name FROM EXAM_TASK t WHERE t.EXEC_DEPT_NAME IS NOT NULL AND (@PARENT_VALUE = '''' OR t.SYSTEM_SOURCE_NO = @PARENT_VALUE) ORDER BY t.EXEC_DEPT_NAME', '获取执行科室列表'),
('category', 'SELECT DISTINCT t.EXAM_CATEGORY_NAME as code, t.EXAM_CATEGORY_NAME as name FROM EXAM_TASK t WHERE t.EXAM_CATEGORY_NAME IS NOT NULL AND (@PARENT_VALUE = '''' OR t.SYSTEM_SOURCE_NO = @PARENT_VALUE) ORDER BY t.EXAM_CATEGORY_NAME', '获取检查类型列表'),
('patientType', 'SELECT DISTINCT t.ENCOUNTER_TYPE_NAME as code, t.ENCOUNTER_TYPE_NAME as name FROM EXAM_TASK t WHERE t.ENCOUNTER_TYPE_NAME IS NOT NULL AND (@PARENT_VALUE = '''' OR t.SYSTEM_SOURCE_NO = @PARENT_VALUE) ORDER BY t.ENCOUNTER_TYPE_NAME', '获取病人类型列表'),
('resultStatus', 'SELECT DISTINCT REPORT_RESULT_STATUS as code, REPORT_RESULT_STATUS as name FROM EXAM_REPORT WHERE REPORT_RESULT_STATUS IS NOT NULL ORDER BY REPORT_RESULT_STATUS', '获取结果状态列表');

GO

CREATE PROCEDURE usp_GetQueryConfig
AS
BEGIN
    SELECT ID, FIELD_NAME, DISPLAY_NAME, IS_VISIBLE, IS_MULTIPLE, SORT_ORDER, PARENT_FIELD, DEFAULT_VALUE, PLACEHOLDER, IS_ACTIVE
    FROM tjfx_QUERY_CONFIG
    WHERE IS_ACTIVE = 1
    ORDER BY SORT_ORDER;
END;

GO

CREATE PROCEDURE usp_SafeExecuteDynamicQuery
    @FieldName NVARCHAR(50),
    @ParentValue NVARCHAR(200) = ''
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @AllowedSQL NVARCHAR(MAX);

    SELECT @AllowedSQL = ALLOWED_SQL
    FROM tjfx_QUERY_WHITELIST
    WHERE FIELD_NAME = @FieldName AND IS_ACTIVE = 1;

    IF @AllowedSQL IS NULL
    BEGIN
        RAISERROR('字段 %s 不在白名单中，无法执行查询', 16, 1, @FieldName);
        RETURN;
    END

    DECLARE @ParamDef NVARCHAR(500);
    SET @ParamDef = '@PARENT_VALUE NVARCHAR(200)';

    BEGIN TRY
        EXEC sp_executesql @AllowedSQL, @ParamDef, @PARENT_VALUE = @ParentValue;
    END TRY
    BEGIN CATCH
        DECLARE @ErrorMessage NVARCHAR(4000);
        DECLARE @ErrorSeverity INT;
        DECLARE @ErrorState INT;

        SELECT
            @ErrorMessage = ERROR_MESSAGE(),
            @ErrorSeverity = ERROR_SEVERITY(),
            @ErrorState = ERROR_STATE();

        RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);
    END CATCH
END;

GO

CREATE PROCEDURE usp_AddQueryConfig
    @FieldName NVARCHAR(50),
    @DisplayName NVARCHAR(100),
    @QuerySql NVARCHAR(MAX),
    @IsVisible BIT = 1,
    @IsMultiple BIT = 0,
    @SortOrder INT = 0,
    @ParentField NVARCHAR(50) = NULL,
    @DefaultValue NVARCHAR(200) = NULL,
    @Placeholder NVARCHAR(100) = NULL,
    @Description NVARCHAR(200) = NULL
AS
BEGIN
    BEGIN TRANSACTION;

    BEGIN TRY
        INSERT INTO tjfx_QUERY_CONFIG (FIELD_NAME, DISPLAY_NAME, QUERY_SQL, IS_VISIBLE, IS_MULTIPLE, SORT_ORDER, PARENT_FIELD, DEFAULT_VALUE, PLACEHOLDER)      
        VALUES (@FieldName, @DisplayName, @QuerySql, @IsVisible, @IsMultiple, @SortOrder, @ParentField, @DefaultValue, @Placeholder);

        INSERT INTO tjfx_QUERY_WHITELIST (FIELD_NAME, ALLOWED_SQL, DESCRIPTION) 
        VALUES (@FieldName, @QuerySql, @Description);

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
        DECLARE @ErrorMessage NVARCHAR(4000);
        SELECT @ErrorMessage = ERROR_MESSAGE();
        RAISERROR('添加配置失败: %s', 16, 1, @ErrorMessage);
    END CATCH
END;

GO

CREATE PROCEDURE usp_UpdateQueryConfig
    @ID INT,
    @DisplayName NVARCHAR(100) = NULL,
    @QuerySql NVARCHAR(MAX) = NULL,
    @IsVisible BIT = NULL,
    @IsMultiple BIT = NULL,
    @SortOrder INT = NULL,
    @ParentField NVARCHAR(50) = NULL,
    @DefaultValue NVARCHAR(200) = NULL,
    @Placeholder NVARCHAR(100) = NULL,
    @IsActive BIT = NULL,
    @Description NVARCHAR(200) = NULL
AS
BEGIN
    BEGIN TRANSACTION;

    BEGIN TRY
        UPDATE tjfx_QUERY_CONFIG
        SET
            DISPLAY_NAME = ISNULL(@DisplayName, DISPLAY_NAME),
            QUERY_SQL = ISNULL(@QuerySql, QUERY_SQL),
            IS_VISIBLE = ISNULL(@IsVisible, IS_VISIBLE),
            IS_MULTIPLE = ISNULL(@IsMultiple, IS_MULTIPLE),
            SORT_ORDER = ISNULL(@SortOrder, SORT_ORDER),
            PARENT_FIELD = ISNULL(@ParentField, PARENT_FIELD),
            DEFAULT_VALUE = ISNULL(@DefaultValue, DEFAULT_VALUE),
            PLACEHOLDER = ISNULL(@Placeholder, PLACEHOLDER),
            IS_ACTIVE = ISNULL(@IsActive, IS_ACTIVE),
            UPDATE_TIME = GETDATE()
        WHERE ID = @ID;

        IF @QuerySql IS NOT NULL OR @Description IS NOT NULL
        BEGIN
            UPDATE tjfx_QUERY_WHITELIST
            SET
                ALLOWED_SQL = ISNULL(@QuerySql, ALLOWED_SQL),
                DESCRIPTION = ISNULL(@Description, DESCRIPTION)
            WHERE FIELD_NAME = (SELECT FIELD_NAME FROM tjfx_QUERY_CONFIG WHERE ID = @ID);
        END

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
        DECLARE @ErrorMessage NVARCHAR(4000);
        SELECT @ErrorMessage = ERROR_MESSAGE();
        RAISERROR('更新配置失败: %s', 16, 1, @ErrorMessage);
    END CATCH
END;

GO

CREATE PROCEDURE usp_DeleteQueryConfig
    @ID INT
AS
BEGIN
    BEGIN TRANSACTION;

    BEGIN TRY
        DECLARE @FieldName NVARCHAR(50);
        SELECT @FieldName = FIELD_NAME FROM tjfx_QUERY_CONFIG WHERE ID = @ID;   

        UPDATE tjfx_QUERY_CONFIG
        SET IS_ACTIVE = 0, UPDATE_TIME = GETDATE()
        WHERE ID = @ID;

        UPDATE tjfx_QUERY_WHITELIST
        SET IS_ACTIVE = 0
        WHERE FIELD_NAME = @FieldName;

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
        DECLARE @ErrorMessage NVARCHAR(4000);
        SELECT @ErrorMessage = ERROR_MESSAGE();
        RAISERROR('删除配置失败: %s', 16, 1, @ErrorMessage);
    END CATCH
END;